name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: EAS build
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build android preview and download artifacts
        run: |
          apk_url=$(eas build --platform android --profile preview --non-interactive | grep ".apk")
          echo -e "DEBUG: apk url is: $apk_url"
          wget -O debug.apk $apk_url

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: debug.apk
          path: debug.apk
